server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Hym2050865
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: Hym2050865
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl